Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/ubuntu/bry/cogs/accounting.py", line 152, in restock
    await interaction.response.send_message("You do not have permission to use this command.", ephemeral=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'restock' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/home/ubuntu/bry/bot.py", line 49, in on_app_command_error
    await interaction.response.send_message(embed=embed, ephemeral=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f08f1188b80>, 1178256.53719202)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f08f11811e0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4659834b20>, 1178257.928362846)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f465982cf10>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fce22e54b20>, 1178259.299355783)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fce22e50e50>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4eac044640>, 1178260.658133718)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4eac03d000>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fedfabb0b20>, 1178261.985790378)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fedfaba9030>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7faae58a4ac0>, 1178263.315065252)]']
connector: <aiohttp.connector.TCPConnector object at 0x7faae589d1b0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4459028ac0>, 1178264.708405969)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4459024d30>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4aa7088b20>, 1178266.003453918)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4aa70814b0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f30dfc28ac0>, 1178267.217418207)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f30dfc21300>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f10cd888b20>, 1178268.448458554)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f10cd881450>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc1800a8b20>, 1178269.896544144)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fc1800a4df0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4bd9c2cac0>, 1178271.125670578)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4bd9c251e0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f59c7aa8b20>, 1178272.423455663)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f59c7aa1480>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc635348ac0>, 1178273.748393049)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fc635341690>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f3ec9eb4b20>, 1178275.091397077)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f3ec9ead660>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fbacb8b4ac0>, 1178276.38109049)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fbacb8ad510>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4477e2cac0>, 1178277.69869252)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4477e24e20>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f7239f84b20>, 1178279.000491147)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f7239f7cfa0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f60092a8b20>, 1178280.257032978)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f60092a4c40>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff264fc0b20>, 1178281.569671945)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff264fb8eb0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1e06a88b20>, 1178282.87147914)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1e06a814b0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fed34f84ac0>, 1178284.174976964)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fed34f7d390>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f328eb88b20>, 1178285.444393487)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f328eb81000>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f381b4b4ac0>, 1178286.781142292)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f381b4ad5d0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f254e834b20>, 1178288.107177675)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f254e82d420>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb420254ac0>, 1178289.415649889)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb42024d3c0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb1bea94b20>, 1178290.753787198)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb1bea98970>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f50edc84b20>, 1178291.986955406)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f50edc7d120>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5ad04a8b20>, 1178293.263955895)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5ad04a0df0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f29eb098b20>, 1178294.632781499)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f29eb091540>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff1809c0ac0>, 1178295.94721867)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff1809b95a0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4ea7178ac0>, 1178297.268206501)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4ea7171480>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4f121c4b80>, 1178298.570303004)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4f121bd2a0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc6c4cb4ac0>, 1178299.907386082)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fc6c4cad480>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7eff530a4b20>, 1178301.234229032)]']
connector: <aiohttp.connector.TCPConnector object at 0x7eff530a8910>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/bry/main.py", line 13, in main
    await bot.start(os.getenv("DISCORD_TOKEN"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 779, in start
    await self.login(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 623, in login
    await self.setup_hook()
  File "/home/ubuntu/bry/bot.py", line 64, in setup_hook
    from cogs.accounting import Accounting
  File "/home/ubuntu/bry/cogs/accounting.py", line 358
    return data
TabError: inconsistent use of tabs and spaces in indentation
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f31ab2b4b20>, 1178302.615465806)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f31ab2b0df0>
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/bry/main.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
